# Generated by Django 5.0.6 on 2024-05-29 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created',)},
        ),
    ]
