# Generated by Django 5.0.6 on 2024-05-29 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 30, 19, 34, 55, 231016)),
        ),
    ]
