# Generated by Django 5.0.6 on 2024-05-29 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_expires'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='expires',
        ),
    ]
