# Generated by Django 5.0.6 on 2024-05-29 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_expires'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-updated', '-paid')},
        ),
    ]
